In [ ]:
# 股票和期货数据的复权处理

In [15]:
import pandas as pd

# 模拟数据（包含换月，open/close）
df = pd.DataFrame({
    'date': pd.date_range('2024-01-01', periods=7),
    'contract': ['IF2401', 'IF2401', 'IF2402', 'IF2402', 'IF2403', 'IF2403', 'IF2403'],
    'open':    [100.0, 101.5,  95.0,  97.0, 110.0, 113.0, 116.0],
    'close':   [101.0, 102.0,  96.0,  98.0, 112.0, 114.0, 117.0],
}).set_index('date')

In [ ]:
df

           contract   open  close
date
2024-01-01   IF2401  100.0  101.0
2024-01-02   IF2401  101.5  102.0
2024-01-03   IF2402   95.0   96.0
2024-01-04   IF2402   97.0   98.0
2024-01-05   IF2403  110.0  112.0
2024-01-06   IF2403  113.0  114.0
2024-01-07   IF2403  116.0  117.0

In [25]:
df['adj_factor'] = 1.0  # 初始化，末尾行的复权因子为1.0（即不动）

for i in range(len(df) - 1, 0, -1):
    prev_contract = df.iloc[i - 1]['contract']
    curr_contract = df.iloc[i]['contract']
    
    if prev_contract != curr_contract:
        print(f'当前的日期是{df.index[i]}')
        print(f'当前合约是{curr_contract},之前一天的合约是{prev_contract}')
        prev_close = df.iloc[i - 1]['close']
        curr_open  = df.iloc[i]['open']
        
        if prev_close and prev_close > 0:
            factor = curr_open / prev_close
            print(f'当天开盘价{curr_open},除以前一天收盘价{prev_close}，得到复权因子{factor}')
            df.loc[:df.index[i - 1], 'adj_factor'] *= factor
        print(df)
        print('-------------------------------------')
        

# 计算复权收盘价
df['adj_close'] = df['close'] * df['adj_factor']

当前的日期是2024-01-05 00:00:00
当前合约是IF2403,之前一天的合约是IF2402
当天开盘价110.0,除以前一天收盘价98.0，得到复权因子1.1224489795918366
           contract   open  close  adj_factor   adj_close
date
2024-01-01   IF2401  100.0  101.0    1.122449  105.587235
2024-01-02   IF2401  101.5  102.0    1.122449  106.632653
2024-01-03   IF2402   95.0   96.0    1.122449  107.755102
2024-01-04   IF2402   97.0   98.0    1.122449  110.000000
2024-01-05   IF2403  110.0  112.0    1.000000  112.000000
2024-01-06   IF2403  113.0  114.0    1.000000  114.000000
2024-01-07   IF2403  116.0  117.0    1.000000  117.000000
-------------------------------------
当前的日期是2024-01-03 00:00:00
当前合约是IF2402,之前一天的合约是IF2401
当天开盘价95.0,除以前一天收盘价102.0，得到复权因子0.9313725490196079
           contract   open  close  adj_factor   adj_close
date
2024-01-01   IF2401  100.0  101.0    1.045418  105.587235
2024-01-02   IF2401  101.5  102.0    1.045418  106.632653
2024-01-03   IF2402   95.0   96.0    1.122449  107.755102
2024-01-04   IF2402   97.0   98.0    1.122449  110.000000
2024-01-05   IF2403  110.0  112.0    1.000000  112.000000
2024-01-06   IF2403  113.0  114.0    1.000000  114.000000
2024-01-07   IF2403  116.0  117.0    1.000000  117.000000
-------------------------------------

In [26]:
df

           contract   open  close  adj_factor   adj_close
date
2024-01-01   IF2401  100.0  101.0    1.045418  105.587235
2024-01-02   IF2401  101.5  102.0    1.045418  106.632653
2024-01-03   IF2402   95.0   96.0    1.122449  107.755102
2024-01-04   IF2402   97.0   98.0    1.122449  110.000000
2024-01-05   IF2403  110.0  112.0    1.000000  112.000000
2024-01-06   IF2403  113.0  114.0    1.000000  114.000000
2024-01-07   IF2403  116.0  117.0    1.000000  117.000000